'use client';

import * as Dialog from '@radix-ui/react-dialog';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowUpRight, Check, ChevronDown, Copy, Crown, LockKeyhole, Search, Sparkles, X, Zap } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Toaster, toast } from 'sonner';
import { PromptItem, prompts } from '@/lib/prompts';

const providerMeta = { chatgpt:['ChatGPT','bg-emerald-400'], claude:['Claude','bg-orange-300'], gemini:['Gemini','bg-blue-400'], grok:['Grok','bg-zinc-100'], universal:['Universal','bg-violet-400'] } as const;
const categories = ['All','Coding','Marketing','Copywriting','Strategy','Productivity','Data analysis'];
const providers = ['All','ChatGPT','Claude','Gemini','Grok'];

function PromptCard({ prompt, onOpen }: { prompt: PromptItem; onOpen: (p: PromptItem) => void }) {
 const [copied, setCopied] = useState(false);
 const copy = async (e: React.MouseEvent) => { e.stopPropagation(); await navigator.clipboard.writeText(prompt.content); setCopied(true); toast.success('Prompt copied to clipboard!'); setTimeout(()=>setCopied(false),1600); };
 const launch = (e: React.MouseEvent) => { e.stopPropagation(); window.open(`https://chatgpt.com/?q=${encodeURIComponent(prompt.content)}`, '_blank', 'noopener,noreferrer'); };
 const [provider, color] = providerMeta[prompt.primaryProvider];
 return <motion.article layout initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} whileHover={{y:-4}} onClick={()=>onOpen(prompt)} className="glass group relative min-h-[290px] cursor-pointer overflow-hidden rounded-[22px] p-5 transition hover:border-white/20 hover:shadow-glow">
   <div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${color}`}/><span className="text-xs font-medium text-zinc-300">{provider}</span></div><button aria-label="Save prompt" className="rounded-lg p-1.5 text-zinc-500 hover:bg-white/10 hover:text-white"><Sparkles size={16}/></button></div>
   <div className="mt-6"><span className="rounded-full border border-white/10 bg-white/[.035] px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider text-zinc-400">{prompt.category.replace('-', ' ')}</span><h3 className="mt-3 text-lg font-semibold tracking-tight text-white">{prompt.title}</h3><p className="mt-2 text-sm leading-6 text-zinc-400">{prompt.shortDescription}</p></div>
   <div className="mt-5 flex flex-wrap gap-1.5">{prompt.variables?.slice(0,2).map(v=><span key={v.key} className="rounded-md bg-violet-400/10 px-2 py-1 text-[10px] text-violet-200">[{v.label}]</span>)}</div>
   <div className="absolute bottom-0 left-0 right-0 flex items-center justify-between border-t border-white/7 bg-black/15 px-5 py-3.5"><div className="flex items-center gap-2"><button onClick={copy} className="flex items-center gap-1.5 rounded-lg px-2 py-1.5 text-xs text-zinc-300 transition hover:bg-white/10 hover:text-white">{copied?<Check size={14} className="text-emerald-300"/>:<Copy size={14}/>} {copied?'Copied':'Copy'}</button><button onClick={launch} className="flex items-center gap-1.5 rounded-lg px-2 py-1.5 text-xs text-zinc-300 transition hover:bg-white/10 hover:text-white"><ArrowUpRight size={14}/> Open</button></div><span className="text-xs text-zinc-600">{prompt.copyCount.toLocaleString()}</span></div>
   {prompt.isPremium && <div className="absolute inset-x-0 bottom-0 flex h-[45%] items-center justify-center bg-zinc-950/55 backdrop-blur-[3px] opacity-0 transition duration-300 group-hover:opacity-100"><button onClick={(e)=>{e.stopPropagation(); toast('Pro unlocks this prompt', {description:'Get unlimited access to the complete vault.'});}} className="flex items-center gap-2 rounded-full border border-violet-300/30 bg-violet-400/15 px-4 py-2 text-sm font-medium text-violet-100"><LockKeyhole size={14}/> Unlock with Pro</button></div>}
 </motion.article>;
}

function PromptModal({ prompt, onClose }: { prompt: PromptItem | null; onClose: () => void }) {
 const [values,setValues] = useState<Record<string,string>>({});
 if (!prompt) return null;
 const content = prompt.variables?.reduce((text,v)=>text.replaceAll(`{{${v.key.toUpperCase()}}}`,values[v.key] || v.defaultValue || `[${v.label}]`),prompt.content) ?? prompt.content;
 const copy=async()=>{await navigator.clipboard.writeText(content);toast.success('Customized prompt copied!');};
 return <Dialog.Root open={!!prompt} onOpenChange={onClose}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-40 bg-black/70 backdrop-blur-sm"/><Dialog.Content className="fixed left-1/2 top-1/2 z-50 max-h-[88vh] w-[min(720px,calc(100%-2rem))] -translate-x-1/2 -translate-y-1/2 overflow-auto rounded-[26px] border border-white/10 bg-[#14161d] p-6 shadow-2xl"><div className="flex items-start justify-between"><div><Dialog.Title className="text-xl font-semibold">{prompt.title}</Dialog.Title><Dialog.Description className="mt-1 text-sm text-zinc-400">Customize the variables, then send it straight to your model.</Dialog.Description></div><Dialog.Close className="rounded-lg p-2 text-zinc-400 hover:bg-white/10"><X size={18}/></Dialog.Close></div>{prompt.variables?.length ? <div className="mt-6 grid gap-3 sm:grid-cols-2">{prompt.variables.map(v=><label key={v.key} className="text-xs font-medium text-zinc-300">{v.label}<input value={values[v.key]||''} onChange={e=>setValues({...values,[v.key]:e.target.value})} placeholder={v.placeholder} className="mt-1.5 w-full rounded-lg border border-white/10 bg-black/20 px-3 py-2.5 text-sm outline-none placeholder:text-zinc-600 focus:border-violet-400"/></label>)}</div>:null}<pre className="mt-6 whitespace-pre-wrap rounded-xl border border-white/8 bg-black/30 p-4 font-mono text-xs leading-6 text-zinc-300">{content}</pre><div className="mt-5 flex flex-wrap gap-2"><button onClick={copy} className="rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-black"><Copy className="mr-1.5 inline" size={15}/>Copy prompt</button><button onClick={()=>window.open(`https://chatgpt.com/?q=${encodeURIComponent(content)}`,'_blank','noopener,noreferrer')} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm font-medium text-white">Open in ChatGPT <ArrowUpRight className="ml-1 inline" size={15}/></button></div></Dialog.Content></Dialog.Portal></Dialog.Root>;
}

export default function Home() {
 const [query,setQuery]=useState(''); const [provider,setProvider]=useState('All'); const [category,setCategory]=useState('All'); const [selected,setSelected]=useState<PromptItem|null>(null); const [sort,setSort]=useState('Most popular');
 const filtered=useMemo(()=>prompts.filter(p=>(provider==='All'||p.primaryProvider===provider.toLowerCase())&&(category==='All'||p.category===category.toLowerCase().replace(' ','-'))&&(`${p.title} ${p.shortDescription} ${p.category}`).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='Newest'?+new Date(b.createdAt)-+new Date(a.createdAt):b.copyCount-a.copyCount),[query,provider,category,sort]);
 return <main className="noise min-h-screen overflow-hidden"><Toaster theme="dark" richColors position="bottom-right"/><div className="dot-grid pointer-events-none absolute inset-x-0 top-0 h-[610px]"/>
 <nav className="relative mx-auto flex max-w-7xl items-center justify-between px-5 py-6"><a className="flex items-center gap-2 text-lg font-semibold tracking-tight"><span className="grid h-8 w-8 place-items-center rounded-lg bg-gradient-to-br from-violet-400 to-cyan-300 text-vault-950"><Zap size={17} fill="currentColor"/></span>PromptVault</a><div className="hidden items-center gap-7 text-sm text-zinc-400 md:flex"><a href="#library" className="hover:text-white">Explore</a><a href="#how" className="hover:text-white">How it works</a><a href="/pricing" className="hover:text-white">Pricing</a></div><a href="/pricing" className="rounded-full border border-white/10 bg-white/[.06] px-4 py-2 text-sm font-medium hover:bg-white/10">Get Pro <ArrowUpRight className="ml-1 inline" size={14}/></a></nav>
 <section className="relative mx-auto max-w-4xl px-5 pb-20 pt-20 text-center sm:pt-28"><div className="inline-flex items-center gap-2 rounded-full border border-violet-300/15 bg-violet-400/10 px-3 py-1.5 text-xs font-medium text-violet-200"><Sparkles size={13}/> The prompt library for serious builders</div><h1 className="gradient-text mt-7 text-5xl font-semibold tracking-[-.055em] sm:text-7xl">Supercharge your AI workflow with battle-tested prompts.</h1><p className="mx-auto mt-6 max-w-2xl text-base leading-7 text-zinc-400 sm:text-lg">The sharpest system and user prompts for teams building what matters. Tested across the models you use every day.</p><div className="glass mx-auto mt-9 flex max-w-2xl items-center rounded-2xl p-2 shadow-glow"><Search className="ml-3 text-zinc-500" size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search 1,000+ prompts..." className="min-w-0 flex-1 bg-transparent px-3 py-3 text-sm outline-none placeholder:text-zinc-600"/><button className="rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-black">Search</button></div><div className="mt-6 flex flex-wrap justify-center gap-2">{categories.slice(1,6).map(c=><button key={c} onClick={()=>{setCategory(c);document.getElementById('library')?.scrollIntoView({behavior:'smooth'});}} className="rounded-full border border-white/8 bg-white/[.03] px-3 py-1.5 text-xs text-zinc-400 transition hover:border-white/20 hover:text-white">{c}</button>)}</div></section>
 <section id="library" className="relative mx-auto max-w-7xl px-5 pb-20"><div className="sticky top-3 z-20 mb-8 rounded-2xl border border-white/8 bg-[#101217]/85 p-3 backdrop-blur-xl"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-1">{providers.map(x=><button key={x} onClick={()=>setProvider(x)} className={`rounded-lg px-3 py-2 text-xs font-medium ${provider===x?'bg-white text-black':'text-zinc-400 hover:bg-white/5 hover:text-white'}`}>{x}</button>)}</div><div className="flex items-center gap-2"><span className="text-xs text-zinc-500">Sort</span><button onClick={()=>setSort(sort==='Most popular'?'Newest':'Most popular')} className="flex items-center gap-1 rounded-lg border border-white/8 px-3 py-2 text-xs text-zinc-300">{sort}<ChevronDown size={14}/></button></div></div><div className="mt-3 flex gap-1 overflow-x-auto border-t border-white/7 pt-3">{categories.map(x=><button key={x} onClick={()=>setCategory(x)} className={`whitespace-nowrap rounded-lg px-3 py-1.5 text-xs ${category===x?'bg-violet-400/15 text-violet-200':'text-zinc-500 hover:bg-white/5 hover:text-zinc-200'}`}>{x}</button>)}</div></div><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-violet-300">Curated collection</p><h2 className="mt-1 text-2xl font-semibold">Find your unfair advantage.</h2></div><span className="text-sm text-zinc-500">{filtered.length} prompts</span></div><AnimatePresence mode="popLayout"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(p=><PromptCard key={p.id} prompt={p} onOpen={setSelected}/>)}</div></AnimatePresence>{filtered.length===0&&<div className="py-20 text-center text-zinc-500">No prompts found. Try a different search.</div>}</section>
 <section id="how" className="border-t border-white/7 bg-white/[.02] py-16"><div className="mx-auto grid max-w-7xl gap-8 px-5 md:grid-cols-3">{[['01','Discover what works','Every prompt is structured for a repeatable, high-signal output.'],['02','Make it yours','Drop in your context with guided dynamic variables.'],['03','Ship faster','Copy or launch directly into ChatGPT in one click.']].map(([num,title,text])=><div key={num}><span className="text-sm font-semibold text-violet-300">{num}</span><h3 className="mt-3 text-lg font-medium">{title}</h3><p className="mt-2 max-w-xs text-sm leading-6 text-zinc-500">{text}</p></div>)}</div></section>
 <PromptModal prompt={selected} onClose={()=>setSelected(null)}/></main>;
}
