export type AIProvider = 'chatgpt' | 'claude' | 'gemini' | 'grok' | 'universal';
export type PromptCategory = 'coding' | 'marketing' | 'copywriting' | 'strategy' | 'productivity' | 'creative' | 'data-analysis';
export interface PromptItem { id: string; slug: string; title: string; shortDescription: string; category: PromptCategory; primaryProvider: AIProvider; supportedProviders: AIProvider[]; content: string; variables?: { key: string; label: string; placeholder: string; defaultValue?: string }[]; isPremium: boolean; copyCount: number; featured?: boolean; createdAt: string; }
export const prompts: PromptItem[] = [
 { id:'1',slug:'staff-engineer-review',title:'Staff Engineer Code Review',shortDescription:'Surface correctness, maintainability, and architectural risks before they ship.',category:'coding',primaryProvider:'claude',supportedProviders:['claude','chatgpt'],isPremium:false,copyCount:2841,featured:true,createdAt:'2026-09-10',variables:[{key:'code',label:'Paste code',placeholder:'function...',defaultValue:'// Paste the code to review here'},{key:'context',label:'Product context',placeholder:'What does this change do?'}],content:'Act as a staff-level software engineer performing a rigorous pull request review.\n\nProduct context: {{context}}\n\nCode to review:\n{{code}}\n\nFirst summarize the intent. Then assess correctness, security, performance, test coverage, API design, and maintainability. For every issue, give severity (blocker/high/medium/low), precise evidence, and a concrete fix. Do not praise without evidence. End with a merge recommendation and the three highest-leverage next steps.' },
 { id:'2',slug:'conversion-landing-page',title:'Conversion Landing Page Architect',shortDescription:'Turn product intelligence into a sharp, high-converting page narrative.',category:'copywriting',primaryProvider:'chatgpt',supportedProviders:['chatgpt','grok'],isPremium:false,copyCount:1936,featured:true,createdAt:'2026-09-06',variables:[{key:'product',label:'Product',placeholder:'Describe your product'},{key:'audience',label:'Target audience',placeholder:'Who is this for?'}],content:'You are a conversion copywriter known for crisp, specific SaaS landing pages. Create a complete page outline for {{product}} targeted at {{audience}}. Include: above-the-fold headline options, subhead, CTA, objection-handling proof bar, problem agitation, benefit-led feature sections, social proof prompts, FAQ, and closing CTA. Use concrete language; avoid clichés and unsupported claims. Explain the persuasion job of each section in one sentence.' },
 { id:'3',slug:'competitive-moat',title:'Competitive Moat Analysis',shortDescription:'Map defensibility, strategic threats, and 90-day moves for executive teams.',category:'strategy',primaryProvider:'gemini',supportedProviders:['gemini','claude','chatgpt'],isPremium:true,copyCount:1280,createdAt:'2026-09-15',variables:[{key:'company',label:'Company',placeholder:'Company and market context'}],content:'Act as a strategy partner. Analyze {{company}} through the lenses of switching costs, network effects, scale economies, proprietary data, brand, and distribution. State assumptions explicitly. Deliver a moat scorecard, credible competitor threats, leading indicators to monitor, and a prioritized 90-day plan. Separate facts, inferences, and open questions.' },
 { id:'4',slug:'sql-analyst',title:'SQL Insight Investigator',shortDescription:'Convert a business question into robust, explainable analytics queries.',category:'data-analysis',primaryProvider:'gemini',supportedProviders:['gemini','chatgpt'],isPremium:true,copyCount:972,createdAt:'2026-09-12',variables:[{key:'schema',label:'Database schema',placeholder:'tables, columns, relationships'},{key:'question',label:'Business question',placeholder:'What do you want to learn?'}],content:'You are a senior analytics engineer. Given this schema: {{schema}}\n\nAnswer this business question: {{question}}\n\nClarify ambiguities first. Then write production-safe SQL with CTEs, explicit assumptions, date boundaries, null handling, and comments. Explain how to validate the result, likely sources of bias, and one useful follow-up cut.' },
 { id:'5',slug:'real-time-sentiment',title:'Unfiltered Market Signal Scan',shortDescription:'Challenge the consensus and turn live conversation into actionable signal.',category:'marketing',primaryProvider:'grok',supportedProviders:['grok','chatgpt'],isPremium:true,copyCount:746,createdAt:'2026-09-17',variables:[{key:'topic',label:'Topic or brand',placeholder:'e.g. AI video generation'}],content:'Act as a skeptical market intelligence analyst. For {{topic}}, synthesize the strongest bullish and bearish narratives currently circulating. Identify sentiment clusters, contrarian takes, evidence quality, and claims requiring verification. Produce an executive brief with signal vs. noise labels, watchlist questions, and three experiments to run this week. Be candid; never invent sources.' },
 { id:'6',slug:'deep-work-os',title:'Deep Work Operating System',shortDescription:'Design a realistic weekly execution cadence that protects your best hours.',category:'productivity',primaryProvider:'universal',supportedProviders:['universal','chatgpt','claude'],isPremium:false,copyCount:1554,createdAt:'2026-08-28',variables:[{key:'goals',label:'Goals',placeholder:'Your top goals and deadlines'}],content:'You are an elite executive coach. Build a humane, high-output weekly operating system around these goals: {{goals}}. Ask up to three clarifying questions if required. Then propose time blocks, a daily shutdown ritual, a task-triage rule, a meeting policy, and a Friday review. Design for consistency, not heroic willpower.' }
];
